# fly.toml app configuration file generated for project-imc on 2025-04-23T20:45:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "project-imc"
primary_region = "gru"  # São Paulo

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[metrics]
  port = 8080
  path = "/metrics"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = "443"
    handlers = ["tls", "http"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false
    [services.http_checks.headers]
      X-Forwarded-Proto = "https"

[mounts]
  source="imc_data"
  destination="/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
