app = "furious_imc"
primary_region = "iad"

[deploy]
  release_command = ""

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80